package com.github.wechat.ilink.bot.travelrag;

import java.util.List;

/** Serializable local vector index generated by {@link TravelRagIndexBuilder}. */
public record TravelVectorIndex(
    String model,
    int dimension,
    String generatedAt,
    String dataNotice,
    List<TravelKnowledgeChunk> chunks) {

  public TravelVectorIndex {
    chunks = chunks == null ? List.of() : List.copyOf(chunks);
  }
}
